### ISSUE TITLE
create content pages for metadata fields

### ISSUE THREAD

**Issue by rococodogs** [LafayetteCollegeLibraries/metadata-guidelines#1]
## Descriptive Metadata
- Abstract
- Academic Department
- Associated Date
- Alternative Title
- Bibliographic Citation
- Contributor
- Creator
- Date
- Date Scope Note
- Description
- Division
- Donor
- Editor
- Extent
- Inscription
- Issued
- Keyword
- Language
- Location
- Organization
- Physical Medium
- Publisher
- Related Resource
- Repository Location
- Requested By
- Research Assistance
- Resource Type
- Source
- Sponsor
- Subject
- Subtitle
- Title

## Administrative Metadata
- Note
- Rights Holder
- Rights Statement
- Standard Identifier

**Comment by jacksodl23** [comment]
All of the content pages have been generated. They are all first drafts, but I'm going to close this issue since pages exist for all of the metadata fields listed above.
