### ISSUE TITLE
Images not displaying

### ISSUE THREAD

**Issue by jacksodl23** [LafayetteCollegeLibraries/metadata-guidelines#3]
Images on the "language," "subject," and "standard identifier" pages are not displaying. They previously displayed while the site was being run locally, but the images do not display on the public-facing version. Nor do they display on a local server anymore.

**Comment by rococodogs** [comment]
not sure if you saw this, but looks like this could be an issue with deploying to a path: https://github.com/gohugoio/hugo/issues/7714
